version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: "@babel/core"
      - dependency-name: "@babel/runtime"
      - dependency-name: "@react-native-community/eslint-config"
      - dependency-name: "eslint"
      - dependency-name: "jest"
      - dependency-name: "metro-react-native-babel-preset"
      - dependency-name: "react-test-renderer"
      - dependency-name: "react"
      - dependency-name: "react-native"
